### ISSUE TITLE
关于数据问题

### ISSUE THREAD

**Issue by yeyupiaoling** [SmartLi8/stella#10]
您好，想问一下我只有一份下面格式的数据集，该如何使用
```
{"txt1":"问题", "txt2":"答案", "hard_negs": ["负样本"]}
```

项目要这么多的数据集，他们是什么意思呢？
```yaml
in_batch_train_paths:
  # synthetic_qp里的qp还是bge的向量
  synthetic_qp:
    - ./data/v2/wudao_synthetic_alpaca2_hfl_0_100000_vec_neg.jsonl
    - ./data/v2/m3e_synthetic_alpaca2_hfl_0_100000_vec_neg.jsonl
  # normal里的hard neg默认是bm25
  normal:
    - ./data/v2/m3e_long_length_hard_neg.jsonl
    - ./data/v2/wudao_long_length_hard_neg.jsonl

pair_train_paths:
  binclf:
    - ./data/v2/binclf_data.jsonl
  nli:
    - ./data/v2/nli_data.jsonl
```
